#!/usr/bin/env bash
set -euo pipefail
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
PREFIX_DIR="$TMP/prefix"
CARGO_HOME_DIR="$TMP/cargo"
FAKE_BIN="$TMP/fake-bin"
mkdir -p "$PREFIX_DIR/bin" "$CARGO_HOME_DIR/bin" "$FAKE_BIN"
printf '#!/usr/bin/env bash\nexit 0\n' > "$CARGO_HOME_DIR/bin/repak"
chmod 0755 "$CARGO_HOME_DIR/bin/repak"
printf '#!/usr/bin/env bash\nexit 0\n' > "$FAKE_BIN/python3"
chmod 0755 "$FAKE_BIN/python3"
PATH="$FAKE_BIN:$CARGO_HOME_DIR/bin:$PATH" PREFIX="$PREFIX_DIR" CARGO_HOME="$CARGO_HOME_DIR" SKIP_PACKAGES=1 bash "$ROOT/install-termux.sh"
REAL_PATH="/usr/local/bin:/usr/bin:/bin"
PAKFORGE_NO_UPDATE=1 PATH="$PREFIX_DIR/bin:$REAL_PATH" bash "$PREFIX_DIR/bin/pakforge" --version | grep -Fx 'PakForge 1.3.8'
command -v "$PREFIX_DIR/bin/tool" >/dev/null
grep -Fq 'pakforge_setup.py' "$PREFIX_DIR/bin/pakforge"
grep -Fq 'nohup python3' "$PREFIX_DIR/bin/pakforge"
grep -Fq 'setup-status' "$PREFIX_DIR/bin/pakforge"
grep -Fq 'PAKFORGE_DEFER_SETUP=1' "$ROOT/bootstrap.sh"
grep -Fq 'PakForge Launcher — OPEN' "$ROOT/bootstrap.sh"
grep -Fq 'remaining_percent' "$ROOT/bootstrap.sh"
grep -Fq 'progress_bar' "$ROOT/bootstrap.sh"
grep -Fq 'run_with_heartbeat' "$ROOT/bootstrap.sh"
grep -Fq 'pkg update -y' "$ROOT/bootstrap.sh"
grep -Fq 'git clone --depth 1' "$ROOT/bootstrap.sh"
grep -Fq 'elapsed_seconds' "$ROOT/bootstrap.sh"
grep -Fq 'updated_at' "$ROOT/bootstrap.sh"
grep -Fq 'heartbeat_count' "$ROOT/bootstrap.sh"
grep -Fq 'eta_seconds' "$ROOT/bootstrap.sh"
grep -Fq 'downloaded_bytes' "$ROOT/bootstrap.sh"
grep -Fq 'lock_is_live' "$ROOT/bootstrap.sh"
grep -Fq 'percent' "$ROOT/pakforge_setup.py"
grep -Fq 'eta_seconds' "$ROOT/pakforge_setup.py"
grep -Fq 'heartbeat_count' "$ROOT/pakforge_setup.py"
grep -Fq 'updated_at' "$ROOT/pakforge_setup.py"
grep -Fq 'SPINNER' "$ROOT/pakforge_first_run.py"
grep -Fq 'format_bytes' "$ROOT/pakforge_first_run.py"
grep -Fq '\033[H\033[J' "$ROOT/pakforge_first_run.py"
grep -Fq 'exec "$PREFIX_DIR/bin/pakforge"' "$ROOT/bootstrap.sh"
grep -Fq 'UE4TOOL_LEGACY' "$PREFIX_DIR/bin/tool"
grep -Fq "exec \"$PREFIX_DIR/bin/pakforge\"" "$PREFIX_DIR/bin/tool"
UE4TOOL_LEGACY=1 PATH="$PREFIX_DIR/bin:$REAL_PATH" bash "$PREFIX_DIR/bin/tool" --help
printf '%s\n' 'launcher-tests-ok'
