#!/usr/bin/env bash
set -euo pipefail
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
PREFIX_DIR="$TMP/prefix"
CARGO_HOME_DIR="$TMP/cargo"
FAKE_BIN="$TMP/fake-bin"
mkdir -p "$PREFIX_DIR/bin" "$CARGO_HOME_DIR/bin" "$FAKE_BIN"
printf '#!/usr/bin/env bash\nexit 0\n' > "$CARGO_HOME_DIR/bin/repak"
chmod 0755 "$CARGO_HOME_DIR/bin/repak"
printf '#!/usr/bin/env bash\nexit 0\n' > "$FAKE_BIN/python3"
chmod 0755 "$FAKE_BIN/python3"
PATH="$FAKE_BIN:$CARGO_HOME_DIR/bin:$PATH" PREFIX="$PREFIX_DIR" CARGO_HOME="$CARGO_HOME_DIR" SKIP_PACKAGES=1 bash "$ROOT/install-termux.sh"
REAL_PATH="/usr/local/bin:/usr/bin:/bin"
PAKTOOL_NO_UPDATE=1 PATH="$PREFIX_DIR/bin:$REAL_PATH" bash "$PREFIX_DIR/bin/tool" --version | grep -Fx 'Paktool 1.4.0'
grep -Fq 'paktool_setup.py' "$PREFIX_DIR/bin/tool"
grep -Fq 'nohup python3' "$PREFIX_DIR/bin/tool"
grep -Fq 'setup-status' "$PREFIX_DIR/bin/tool"
grep -Fq 'update-status' "$PREFIX_DIR/bin/tool"
grep -Fq 'git fetch --quiet origin main' "$PREFIX_DIR/bin/tool"
grep -Fq 'auto-stashed local changes' "$PREFIX_DIR/bin/tool"
grep -Fq 'paktool-local-backup-' "$PREFIX_DIR/bin/tool"
grep -Fq 'Latest origin/main downloaded' "$PREFIX_DIR/bin/tool"
grep -Fq 'PAKTOOL_ROOT_DIR="/sdcard/Paktool"' "$PREFIX_DIR/bin/tool"
grep -Fq 'SDCARD_PAK_DIR="$PAKTOOL_ROOT_DIR/PAK"' "$PREFIX_DIR/bin/tool"
grep -Fq 'SDCARD_EDIT_DIR="$PAKTOOL_ROOT_DIR/EDIT"' "$PREFIX_DIR/bin/tool"
grep -Fq 'SDCARD_UNPACKED_DIR="$PAKTOOL_ROOT_DIR/UNPACKED"' "$PREFIX_DIR/bin/tool"
grep -Fq 'SDCARD_MODDED_DIR="$PAKTOOL_ROOT_DIR/MODDED"' "$PREFIX_DIR/bin/tool"
grep -Fq 'termux-setup-storage' "$PREFIX_DIR/bin/tool"
grep -Fq 'PAKTOOL_DEFER_SETUP=1' "$ROOT/bootstrap.sh"
grep -Fq 'Paktool Launcher — OPEN' "$ROOT/bootstrap.sh"
grep -Fq 'remaining_percent' "$ROOT/bootstrap.sh"
grep -Fq 'progress_bar' "$ROOT/bootstrap.sh"
grep -Fq 'run_with_heartbeat' "$ROOT/bootstrap.sh"
grep -Fq 'pkg update -y' "$ROOT/bootstrap.sh"
grep -Fq 'pkg install -y curl git python' "$ROOT/bootstrap.sh"
grep -Fq 'git clone --filter=blob:none --sparse --depth 1' "$ROOT/bootstrap.sh"
grep -Fq 'sparse-checkout set --no-cone' "$ROOT/bootstrap.sh"
grep -Fq 'elapsed_seconds' "$ROOT/bootstrap.sh"
grep -Fq 'updated_at' "$ROOT/bootstrap.sh"
grep -Fq 'heartbeat_count' "$ROOT/bootstrap.sh"
grep -Fq 'eta_seconds' "$ROOT/bootstrap.sh"
grep -Fq 'downloaded_bytes' "$ROOT/bootstrap.sh"
grep -Fq 'lock_is_live' "$ROOT/bootstrap.sh"
grep -Fq 'percent' "$ROOT/paktool_setup.py"
grep -Fq 'eta_seconds' "$ROOT/paktool_setup.py"
grep -Fq 'heartbeat_count' "$ROOT/paktool_setup.py"
grep -Fq 'updated_at' "$ROOT/paktool_setup.py"
grep -Fq 'SPINNER' "$ROOT/paktool_first_run.py"
grep -Fq 'format_bytes' "$ROOT/paktool_first_run.py"
grep -Fq '\033[H\033[J' "$ROOT/paktool_first_run.py"
grep -Fq 'exec "$PREFIX_DIR/bin/tool"' "$ROOT/bootstrap.sh"
printf '%s\n' 'launcher-tests-ok'
